allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msgpackr-extract: true
  redux-react: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
