catalog:
  '@effect/typeclass': ^0.37.0
  '@effect/vitest': ^0.26.0
  '@eslint/js': ^9.37.0
  '@fast-check/vitest': ^0.2.2
  '@storybook/addon-docs': 9.1.10
  '@storybook/react-vite': ^9.1.10
  '@testing-library/jest-dom': ^6.9.1
  '@tailwindcss/cli': ^4.1.14
  '@testing-library/react': ^16.3.0
  '@tsconfig/node24': ^24.0.1
  '@tsconfig/strictest': ^2.0.6
  '@tsconfig/vite-react': ^7.0.1
  '@types/node': ^24.7.0
  '@types/react': ^19.2.1
  '@types/react-dom': ^19.2.0
  '@vitejs/plugin-react': ^5.0.4
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  dependency-cruiser: ^17.0.2
  effect-schema-viz: ^1.0.10
  effect-ts-laws: ^1.3.19
  effect: ^3.18.4
  effect-tree: ^1.0.32
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react-hooks: ^6.1.1
  eslint-plugin-react-refresh: ^0.4.23
  eslint-plugin-react: ^7.37.5
  eslint-plugin-sonarjs: ^3.0.5
  eslint-plugin-unicorn: ^61.0.2
  eslint: ^9.37.0
  fast-check: ^4.3.0
  globals: ^16.4.0
  happy-dom: ^19.0.2
  jiti: ^2.6.1
  playwright: ^1.56.0
  prettier: ^3.6.2
  react-compinators: ^1.0.55
  react-dom: ^19.2.0
  react: ^19.2.0
  storybook-addon-pseudo-states: ^9.1.10
  storybook: ^9.1.10
  tailwindcss: ^4.1.14
  tsx: ^4.20.6
  tty-strings: ^1.5.2
  typedoc: ^0.28.13
  typescript-eslint: ^8.46.0
  typescript: ^5.9.3
  vite: npm:rolldown-vite@7.1.16
  vitest: 3.2.4
  vitest-browser-react: ^1.0.1

onlyBuiltDependencies:
  - esbuild
