#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

# shellcheck source=dev/lib/_
. "$(dirname "${0}")/lib/_"

echo "# ⚖ Checking…"

pnpm circular &
pnpm typecheck &
pnpm test &
pnpm lint &

wait

show_done 'coverage'
