#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

# shellcheck source=dev/lib/_
. "$(dirname "${0}")/lib/_"

depcruise -c "$CONFIG_DIR"/dependency-cruiser.cjs index.tsx src

show_done 'circular'
