#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

# shellcheck source=dev/lib/_
. "$(dirname "${0}")/lib/_"

clean_dirs=("$DIST_DIR")

for dir in "${clean_dirs[@]}"; do
  if [[ -d "${dir}" ]]; then
    log "🧹 Cleaning “${dir}”"
    rm -rf "${dir}"
  fi
done

show_done 'clean'
