#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

# shellcheck source=dev/lib/_
. "$(dirname "${0}")/lib/_"

eslint --config="$CONFIG_DIR"/eslint.config.ts --fix "${@}"

show_done 'lint:fix'
